### PR TITLE
Task 5 (AWS Simple Storage Service - S3)

### PR DESCRIPTION
**Pull request by candentira**
1. Task: https://github.com/rolling-scopes-school/nodejs-aws-tasks/blob/main/task5-import-to-s3/task.md
2. Screenshot:
3. Links:
importProductsFile: https://ou6esb7r25.execute-api.eu-west-1.amazonaws.com/dev/import
FE PR: https://github.com/candentira/nodejs-aws-fe/pull/5
https://d5vx1ujajushw.cloudfront.net/
4. Done 15.11.2020 / deadline 25.11.2020
5. Score: 3 / 6

Evaluation criteria
Provide your reviewers with the link to the repo, client application and URLs to execute the /import path of the import-service

- [x] 1 - authorization-service is added to the repo, has correct basicAuthorizer lambda and correct serverless.yaml file
- [x] 3 - import-service serverless.yaml file has authorizer configuration for the importProductsFile lambda. Request to the importProductsFile lambda should work only with correct authorization_token being decoded and checked by basicAuthorizer lambda. Response should be in 403 HTTP status if access is denied for this user (invalid authorization_token) and in 401 HTTP status if Authorization header is not provided.
- [ ] 5 - update client application to send Authorization: Basic authorization_token header on import. Client should get authorization_token value from browser localStorage https://developer.mozilla.org/ru/docs/Web/API/Window/localStorage authorization_token = localStorage.getItem('authorization_token')
Additional (optional) tasks
- [ ] +1 - Client application should display alerts for the responses in 401 and 403 HTTP statuses. This behavior should be added to the nodejs-aws-fe-main/src/index.tsx file

### CODE REVIEW

**Comment by Ivanko5417** [comment]
I cannot upload file: 
image
image

All other tasks are fully completed!

**Comment by SychevAndrey** [comment]
I also have a trouble with uploading file. Try to use a computed contentType in the headers in your FE **uploadFile** function like this:
`
import mime from 'mime-types';
const contentType = mime.lookup(file.name);
`

Everything else is great!

**Comment by candentira** [comment]
@Ivanko5417 @SychevAndrey I've done the  changes required in FE repository, but forgot to deploy them to cloudfront, checked only locally.
Now have deployed and rechecked that Upload is working correctly on https://d5vx1ujajushw.cloudfront.net/
Please, recheck!

**Comment by Ivanko5417** [comment]
@candentira I still have problems. I got 403 status code
image

**Comment by candentira** [comment]
@Ivanko5417 It's super strange, everything is working on my side.
image

Could you please try Empty Cache and Hard Reload the page?
In your previous screenshot wrong url was used upon UploadFile button press. Is it still the same?

**Comment by candentira** [comment]
@Ivanko5417 has also checked from Incognito tab. Works for me.
image

**Comment by Ivanko5417** [comment]
I've found the problem:
`        ContentType: 'application/vnd.ms-excel'`
You accept only excel files, I tried to send csv. I think the CSV format is right for this task

**Comment by candentira** [comment]
Have updated ContentType (both BE&FE as on Windows even when you pass .csv file, application/vnd.ms-excel is send to the server).
image
image
image

**Review by ilya-moskovtsev — APPROVED** [review]

**Review by ilya-moskovtsev — APPROVED** [review]

**Pull request merged**
